TESTS = tests/test_sample tests/test_su3 tests/test_buffers

TEMP = $(patsubst %.c,%,$(wildcard $(top_srcdir)/tests/*.c))
TESTMODULES = $(patsubst $(top_srcdir)/%,%,$(TEMP))

TESTFLAGS = -L$(top_builddir)/cu/ -lcu

$(addsuffix .o,$(TESTMODULES)): %.o : $(top_srcdir)/%.c
	${COMPILE} -c $(OPTARGS) $<

# The linking stage needs to be differentiated because different tests rely on
# different modules from the codebase
# Each test itself consists of a number of modules that need to be linked.

# when used as a prerequisite, the wildcard with "tests/test_sample*.c" replaced by "$@*.c" is not evaluated
# correctly, even though it works perfectly in an echo statement, it results in make
# trying to compile all objects in top_srcdir
# we therefore evaluate the wildcard into a variable

TEST_SAMPLE_OBJECTS:=$(patsubst $(top_srcdir)/%.c,%.o,$(wildcard $(top_srcdir)/tests/test_sample*.c))
tests/test_sample: $(TEST_SAMPLE_OBJECTS) $(top_builddir)/cu/libcu.a
	${LINK} $(TEST_SAMPLE_OBJECTS) $(TESTFLAGS)

TEST_SU3_OBJECTS:=$(patsubst $(top_srcdir)/%.c,%.o,$(wildcard $(top_srcdir)/tests/test_su3*.c)) expo.o
tests/test_su3: $(TEST_SU3_OBJECTS) expo.o $(top_builddir)/cu/libcu.a
	${LINK} $(TEST_SU3_OBJECTS) $(TESTFLAGS) -lm

TEST_BUFFERS_OBJECTS:=$(patsubst $(top_srcdir)/%.c,%.o,$(wildcard $(top_srcdir)/tests/test_buffers*.c)) fatal_error.o
tests/test_buffers: $(TEST_BUFFERS_OBJECTS) $(top_builddir)/cu/libcu.a $(top_builddir)/buffers/libbuffers.a
	${LINK} $(TEST_BUFFERS_OBJECTS) $(TESTFLAGS) -lbuffers -L$(top_builddir)/buffers/

# make sure that the regressions directory exists in the tests directory, this is where the tests
# will store output for regression testing
tests: ${TESTS}
	@ cd ${top_builddir}/tests && \
  mkdir -p regressions

