find_library(TM_QMP_LIBS NAMES qmp PATH_SUFFIXES "lib" "lib64")
find_library(TM_QPHIX_LIBS_CODEGEN NAMES "qphix_codegen" PATH_SUFFIXES "lib" "lib64")
find_library(TM_QPHIX_LIBS_SOLVER NAMES "qphix_solver" PATH_SUFFIXES "lib" "lib64")

message("${QMP_DIR}")

find_path(
  TM_QMP_INCLUDE_DIRS
  NAMES qmp.h
  PATH_SUFFIXES "include"
  PATHS "${QMP_DIR}")

find_path(
  TM_QPHIX_INCLUDE_DIRS
  NAMES qphix_config.h
  PATH_SUFFIXES "qphix"
  PATHS "${QPHIX_DIR}")
find_path(
  TM_QPHIX_CODEGEN_INCLUDE_DIRS
  NAMES qpx_utils.h
  PATH_SUFFIXES "qphix_codegen"
  PATHS "${QPHIX_DIR}")

message("${TM_QMP_INCLUDE_DIRS} ${TM_QPHIX_INCLUDE_DIRS} ${TM_QMP_LIBS} ${TM_QPHIX_LIBS_CODEGEN} ${TM_QPHIX_LIBS_SOLVER}")

find_package_handle_standard_args(
  Qphix DEFAULT_MSG TM_QPHIX_LIBS_CODEGEN TM_QPHIX_LIBS_SOLVER TM_QPHIX_INCLUDE_DIRS TM_QMP_LIBS TM_QMP_INCLUDE_DIRS TM_QPHIX_CODEGEN_INCLUDE_DIRS)

if(TM_QMP_LIBS
    AND TM_QPHIX_INCLUDE_DIRS
    AND NOT TARGET tmlqcd::qphix)
  add_library(tmlqcd::qphix INTERFACE IMPORTED)
  set_target_properties(tmlqcd::qphix PROPERTIES INTERFACE_LINK_LIBRARIES
    "${TM_QPHIX_LIBS_CODEGEN};${TM_QPHIX_LIBS_SOLVER};${TM_QMP_LIBS}")
  set_target_properties(tmlqcd::qphix PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
    "${TM_QMP_INCLUDE_DIRS};${TM_QPHIX_INCLUDE_DIRS}/..;${TM_QPHIX_INCLUDE_DIRS};${TM_QPHIX_CODEGEN_INCLUDE_DIRS}")
endif()

mark_as_advanced(TM_QPHIX_LIBRARIES TM_QPHIX_INCLUDE_DIRS TM_QMP_LIBS TM_QMP_INCLUDE_DIRS)
