name: tmlqcd
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    #commit: 
modules: true
description: "tmLQCD dependencies for CSCS CI on MI300A."
version: 2
