gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32 +cuda
      specs: ['libfabric@2.4.0+cuda']
  unify: true
  specs:
  - tmlqcd@master +lemon +quda ^quda@develop +qdp +multigrid +twisted_clover +twisted_mass
  - numdiff
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
